# Set python base image
FROM python:3.8-slim-buster

# Set working directory
WORKDIR /frontend

# Expose port
EXPOSE 8501

# Install packages
COPY poetry.lock pyproject.toml ./
RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry install

# Copy files
COPY frontend frontend

# Run streamlit app
CMD ["streamlit run frontend/streamlit_app.py"]