# Set python base image
FROM python:3.8-slim-buster

# Set working directory
WORKDIR /src

# Expose port
EXPOSE 8000

# Install packages
COPY poetry.lock pyproject.toml ./
RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry install

# Copy files
COPY src/app/ src/app/

# Run fastapi app
CMD ["gunicorn", "app.main:app", "-w" ,"2", "-k", "uvicorn.workers.UvicornWorker", "-b", "0.0.0.0:8000"]
